### ISSUE TITLE
I can't run solana dapp in my computer

### ISSUE THREAD

**Issue by bohdannikita** [webmonster124/string-apend-program-solana#1]
Hi, friends.
I am new to solana and want to learn about solana program.
Recently I am following Nader Dabit's article and I can't run the program and dapp myself.
I hope experienced developer's help.
I am developing by using this article https://dev.to/dabit3/the-complete-guide-to-full-stack-solana-development-with-react-anchor-rust-and-phantom-3291 
Thanks in advance

**Comment by bohdannikita** [comment]
I tried to do "anchor build" but this error shows and I am not sure why this happens. Please help me.

![solana](https://user-images.githubusercontent.com/94215157/194347332-397623d7-1a88-4c77-aecc-a978ecc21607.png)

**Comment by topcook** [comment]
Hi, @webmonster124 
In avm 24.2, ProgramResult is deprecated. You can use "Result<()>" instead of "ProgramResult"
Cheers.

**Comment by bohdannikita** [comment]
Hello, @topcook
Thanks for your help. It works.
Another issue now. I tried to deploy that program in localhost chain and tried to connect to frontend but this error shows.
Would you explain how I can overcome this issue again?
![isssue](https://user-images.githubusercontent.com/94215157/194560457-296cd9e8-4ad2-4d5b-bbbf-74ea1770967f.png)

**Comment by topcook** [comment]
@webmonster124 
Thanks for your reaching out.
That is not solana problem, that is mainly node module problem.
For accounting that issue, you should add buffer to devDependencies in package.json.
And then you should add this statement in App.js file in your solana dapp.
Good luck.
P.S. If you want, I will commit the required changes for your dapp to work.

**Comment by topcook** [comment]
Sorry. I didn't mention this statement in the previous comment.
window.Buffer = window.Buffer || require("buffer").Buffer;

> @webmonster124 Thanks for your reaching out. That is not solana problem, that is mainly node module problem. For accounting that issue, you should add buffer to devDependencies in package.json. And then you should add this statement in App.js file in your solana dapp. Good luck. P.S. If you want, I will commit the required changes for your dapp to work.

**Comment by bohdannikita** [comment]
Thanks, @topcook

**Comment by topcook** [comment]
I updated dapp source code and sent pull request.
Good luck.
